#!/usr/bin/env bash

# Computes the jaccard distance between vectors of 
# unique kmers of two genomes

# Stop at any error
set -eo pipefail

cwd=$(pwd)

echo 
SECONDS=0
g1=false
g2=false
output_folder=ppp
output_file=false
k=17
show_help=false 

# read the options
cmd=$0" "$@
TEMP=`getopt -o 1:2:f:o:k:h: -l genome1:,genome2:,file:,output-folder:,k-size:,help: -n 'ukmers_check' -- "$@"`
eval set -- "$TEMP"

# extract options and their arguments into variables.
while true ; do
    case "$1" in
        -1|--genome1) g1=$2 ; shift 2 ;;
        -2|--genome2) g2=$2 ; shift 2 ;;
        -f|--file) output_file=$2 ; shift 2 ;;
        -o|--output-folder) output_folder=$2 ; shift 2 ;;
        -k|--k-size) k=$2 ; shift 2 ;;
        -h|--help) show_help=true ; shift ;;
        --) shift ; break ;;
        *) echo "$2" "Internal error!" ; exit 1 ;;
    esac
done


if [[
     $g1 == false || $g2 == false
   ]];
then
    show_help=true
    >&2 echo "Mandatory arguments -1 -2"
fi



if [ $show_help == true ];
then
    echo "options:"
    echo "    -1, --genome1             file    Genome to compare"
    echo "    -2, --genome2             file    Genome to compare"
    echo "    -k, --k-size              int     kmers size (def:17)"
    echo "    -o, --output-folder       dir     Output folder"
    exit
fi

mkdir -p $output_folder
cd $output_folder

gs1="${g1%.fa*.gz}"  # Removes .fa
gs2="${g2%.fa*.gz}"
name1="${gs1##*/}"  # Removes path until filename
name2="${gs2##*/}"

echo
echo "==> Genome1: $name1"
echo "==> Genome2: $name2"
echo "==> K size:  $k"
echo "==> Output folder: $output_folder"
echo "==> g1:  $g1"
echo "==> gs1: $gs1"
echo "==> name1: $name1"
echo "==> g2:  $g2"
echo "==> gs2: $gs2"
echo "==> name2: $name2"
echo "=================================================="
echo

cd $cwd

if ! [[ -f "$name1"_"$k"_all ]]; then
        mkdir -p $output_folder/$k$name1
        FastK -k$k -P$output_folder/$k$name1 $g1
        Tabex "$gs1".ktab LIST > "$name1"_"$k"_all
        echo "check1"
fi
if ! [[ -f "$name2"_"$k"_all ]]; then
        mkdir -p $output_folder/$k$name2
        FastK -k$k -P$output_folder/$k$name2 $g2
        Tabex "$gs2".ktab LIST > "$name2"_"$k"_all
        echo "check2"
fi
echo "check3"
if ! [[ -f comp_"$k"_"$name1"_"$name2" ]]; then
    comm  <(awk '$4==1 {print $2}' "$name1"_"$k"_all) \
          <(awk '$4==1 {print $2}' "$name2"_"$k"_all) \
          > comp_"$k"_"$name1"_"$name2"
fi

echo "check4"
# common ukmers


echo $name1 $name2 `cat comp_"$k"_"$name1"_"$name2" | wc -l` `awk -F'\t' '{print $3}' comp_"$k"_"$name1"_"$name2" | sed '/^[[:space:]]*$/d' | wc -l` >> $output_file
